---

- name: ensure tasks run only on selected os releases
  block:

    - name: install the mariadb server and its prerequisites
      ansible.builtin.package:
        name:
          - mariadb-server
          - python3-mysqlclient
        state: present

    - name: enable and start the mariadb service
      ansible.builtin.service:
        name: mariadb.service
        state: started
        enabled: true

    - name: allow external db connections in selinux
      ansible.posix.seboolean:
        name: mysql_connect_any
        state: true
        persistent: true

    - name: expose mysql ports
      ansible.posix.firewalld:
        service: mysql
        state: enabled
        permanent: true
        immediate: true
        offline: true

    - name: remove the test database
      community.mysql.mysql_db:
        name: test
        state: absent
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: remove anonymous accounts
      community.mysql.mysql_user:
        name: ""
        host_all: true
        state: absent
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: set the password for the root account
      community.mysql.mysql_user:
        name: root
        password: r00tb33r
        host_all: true
        login_unix_socket: /var/lib/mysql/mysql.sock

  when: ansible_distribution == "RedHat"

...
