---

- name: ensure tasks run only on selected os releases
  block:

    - name: install the mariadb server
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: enable and start the mariadb service
      ansible.builtin.service:
        name: mariadb.service
        state: started
        enabled: true

    - name: allow external db connections in selinux
      ansible.posix.seboolean:
        name: mysql_connect_any
        state: true
        persistent: true

    - name: expose mysql ports
      ansible.posix.firewalld:
        service: mysql
        state: enabled
        permanent: true
        immediate: true
        offline: true

  when: ansible_distribution == "RedHat"

...
