---

- name: ensure tasks run only on selected os releases
  block:

    - name: install the phpmyadmin application and its prerequisites
      ansible.builtin.package:
        name:
          - phpmyadmin
          - httpd
          - mod_ssl
        state: present

  when: ansible_distribution == "RedHat"

...
