---

- name: ensure tasks run only on selected os releases
  block:

    - name: install the phpmyadmin application and its prerequisites
      ansible.builtin.package:
        name:
          - phpmyadmin
          - httpd
          - mod_ssl
        state: present

    - name: allow apache to access the phpmyadmin location
      community.general.sefcontext:
        target: '/usr/share/phpMyAdmin(/.*)?'
        setype: httpd_sys_rw_content_t
        state: present

    - name: allow apache to make external connections in selinux
      ansible.posix.seboolean:
        name: httpd_can_network_connect
        state: true
        persistent: true

    - name: start the apache service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: expose apache ports
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
        offline: true
      loop:
        - http
        - https

  when: ansible_distribution == "RedHat"

...
